### ISSUE TITLE
Interpolación incorrecta en algún lado

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/Mezclado-de-regiones-en-imagenes-usando-la-ecuacion-de-Poisson#19]
Cuando se calcula la interpolación del oso en la piscina el fondo se cambia de color. Lo que es indicativo de que hay algo mal.

**Comment by Exequielac** [comment]
@BlancaCC Esto puede deberse a la normalización de las imágenes, me pongo a ello

**Comment by BlancaCC** [comment]
@Exequielac

**Comment by BlancaCC** [comment]
@Exequielac Efectivamente era por eso, pero truncado los excesos entre 0 y 255 la imagen tampoco resulta muy buena. 

Se me ocurren dos posibles soluciones:
1- añadir más margen a las imágenes, para que el borde que adapte sea agua con agua. 

2. Creo que los algoritmos funcionaban mejor si estaban las imágenes en el intervalo [0,1] así que habría que convertirlas

**Comment by BlancaCC** [comment]
@BlancaCC La solución 2 ha sido probada por nuestro querido Exequiel y no ha producido cambios notables.

**Comment by BlancaCC** [comment]
@BlancaCC El punto está entonces ¿Por qué se hay regiones que sobrepasan la cota?  

En este caso particular, el agua alrededor del oso es mucho más clara que en la de la piscina, luego cuando la iguala el agua del oso también aumenta "la oscuridad del oso" que ya era lo suficientemente oscuro. 

Como nuestro algoritmo de pintado normaliza la imagen para evitar saturaciones es por ello que visualizamos la imagen con el agua de la imagen objetivo más clara que la original.  Pudiendo afirmar con esto que el algoritmo hace lo esperado. 

¿Y si quisiéramos mantener el color del mar original sin saturar al oso?

La filosofía  aquí es el siguiente:
- ambas son aguas, pero son por naturaleza de tonos más oscuros ( y no necesariamente por la luminosidad que es con lo que trabaja el algoritmo).
- si ese oso real se metiera en la piscina mantendría notablemente su color.

¿Cuál sería entonces la solución correcto?
Oscurecer el agua de alrededor del oso sin modificar (o sin modificar tanto la del oso)

¿Cómo se podría meter al oso sin tocarlo? Estamos ante un problema de segmentación.
