### ISSUE TITLE
Ir transcribiendo información de resumen.md al documento de overlead. Porque hay muchas cosas reciclables

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/Mezclado-de-regiones-en-imagenes-usando-la-ecuacion-de-Poisson#2]

**Comment by BlancaCC** [comment]
Se queda estancada el copieteo de la parte matemática del archivo resumen, porque me apetece seguir avanzando y me da pereza copiar y corregir (sorry) 

(Por cierto, me estoy escuchando ahora esto  https://open.spotify.com/track/6mhQ7eOHaV0ur2ooKTavW1?si=061f3eb0eee14ea6 y estoy más feliz que todo, da gana de comerse el mundo)

**Comment by Exequielac** [comment]
f* = imagen sobre la que se va a pegar
g = imagen que se va a pegar
v = vector de guía
f = función de interpolación

Si v = g, ¿la función de interpolación hace que el pegado sea "realista" en el sentido de que se acoplan los gradientes de ambas imágenes?

**Comment by BlancaCC** [comment]
Entiendo que tu pregunta va sobre cómo entender de manera intuitiva qué se está haciendo. 

Yo diría que en vez de la ecuación que dices sería $v = \nabla g$ (el gradiente de g, es. un vector de $R^2$ que tiene las derivadas parciales de g)
Para que entiendas de dónde viene puedes pensarlo de varia maneras: 
1. Fíjate en que la ecuación a resolver es de la forma 
$$ min_f \int \int _ \Omega | \nabla f - v|^2$$ con condiciones de Dirichlet en el borde. 

¿Qué tiene más sentido que sea v? ¿Qué significaría integrar una imagen? ¿No tendría más sentido integrar su derivada?

2. La intuición de porqué se trabaja con derivadas proviene también de conceptos biológicos, se comenta al principio del paper con el que estamos trabajando y hace además referencia a éster artículo. LAND, E., AND MCCANN, J. 1971. Ligthness and Retinex Theory. J. Opt. Soc. Amer. 61, 1–11. (Un poquito denso) 

Cualquier cosa me dices, que tengas muy buen y positivo día Exequielillo 😊

**Comment by Exequielac** [comment]
Me he leído todo el overleaf, he hecho algunos comentarios en negrita. Corrígeme si no estoy en lo cierto, pero casi todo lo que hay en el resumen ya está en el overleaf. Dicho esto, no sé que más puedo añadir.
