### ISSUE TITLE
[Memoria] Introducción:

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/Mezclado-de-regiones-en-imagenes-usando-la-ecuacion-de-Poisson#38]
Describir ligeramente herramienta y problemas que hemos resuelto con ella.

**Comment by BlancaCC** [comment]
He acabado juntando la introducción con la descripción del problema. 
Introduzco referencias a método vistos en teoría, aunque quizás se podría refinar su explicación. Esto está relacionado con los objetivos #5 #4 . 

No sé si ha quedado demasiado breve, quizás habría que refinarlo al final.

**Comment by BlancaCC** [comment]
En cuanto puedas revísalo Exequiel, son dos líneas del apartado primero de la memoria.

**Comment by Exequielac** [comment]
He hecho una pequeñísima modificación en la introducción. No sé, yo como introducción lo veo bien, tampoco es necesario que sea extenso.

**Comment by Exequielac** [comment]
He extendido un poco la introducción. Agradecería una revisión :D.

**Comment by BlancaCC** [comment]
Entiendo que el nuevo concepto a aportar es: hacer hincapié en la flexibilidad que ofrece la ecuación de Poisson, pe parece bien reforzar la idea. 
Sin embargo creo que todavía no termina de encajar bien cómo se ha enlazado y por otra parte, lo que ofrece la versatilidad es el campo vectorial. 

Aun así he cogido tu concepto y otras cosillas que me han gustado  y lo he integrado al principio. 
A ver si ya te convence 😊

**Comment by Exequielac** [comment]
Yo ya lo veo genial :D. Cierro la issue
