### ISSUE TITLE
[Memoria] Explicación de los conceptos matemáticos.

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/Mezclado-de-regiones-en-imagenes-usando-la-ecuacion-de-Poisson#39]
Tanto base teórica y continua hasta cómo se formula una discretización para ser abordados computacionalmente

**Comment by BlancaCC** [comment]
Añado definiciones y conceptos y bibliografía referente a resultados matemáticos. 
Dejo a medias con un borrador a partir de la sección 2.2.3. 
Esta parte me está resultando bastante tediosa, así que me voy al gimnasio a desconectar. No descarto empezar otro apartado e ir haciendo poco a poco este. 

Espero que tengas un buen día y también hagas deporte 🥰

**Comment by BlancaCC** [comment]
Arreglo problema de la referencia de imágenes #47 

Reviso realizando pequeños cambios en apartado 2.2 y añado saltos de líneas dobles para que no sea una página pegote con todo texto

**Comment by BlancaCC** [comment]
Hecho a falta de revisar

**Comment by Exequielac** [comment]
ESTÁ GENIAL. Dejo la issue abierto porque he visto un TODO relacionado con alguna referencia. Tremendo trabajo.

**Comment by BlancaCC** [comment]
Referenciado el TODO 😇
