### ISSUE TITLE
[Memorial] Copiado prístino

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/Mezclado-de-regiones-en-imagenes-usando-la-ecuacion-de-Poisson#40]
- Fundamento
- Descripción
- Implementación (breve comentario si procede)
- Resultados
- Refinamientos implementados
- Conclusiones
- Especular sobre refinamientos posibles (si procede).

**Comment by BlancaCC** [comment]
@BlancaCC Aquí es necesario además comentar sobre el problema del que nos dimos cuenta: 

La necesidad de que el fondo sea parecido. (ver resultados de issue #19)

**Comment by BlancaCC** [comment]
Comienzo a desarrollar la idea básica, me he tirado más tiempo peleándome con las imágenes que otra cosa 🙁

**Comment by BlancaCC** [comment]
Ya está explicado la técnica de copiado prístino y directo. 
Falta revisarlo cuando se pueda 🥰

**Comment by Exequielac** [comment]
Está todo perfecto. He corregido un par de errores de referencias y minucias. Lo doy por finiquitado :D.
