### ISSUE TITLE
[Memorial] Cálculo de vecinos y discreta Poisson solver

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/Mezclado-de-regiones-en-imagenes-usando-la-ecuacion-de-Poisson#41]
Descripción del cálculo de técnicas como el cálculo de vecinos y discreta Poisson solver

**Comment by BlancaCC** [comment]
Hecho a falta de revisar en apartado 2.3 Discretización del problema.

**Comment by Exequielac** [comment]
Lo revisé antes y se me olvidó cerrar la issue jsjsjsjaja. Todo genial :D, cierro la issue.
