### ISSUE TITLE
[Memoria] Selección e interpolación de las imágenes

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/Mezclado-de-regiones-en-imagenes-usando-la-ecuacion-de-Poisson#42]
Se debe comentar: 
-  El sistema implementado de selección de las imágenes a clonar.
- Posicionamiento de tales regiones en la imagen objetivo.
- Importante comentar lo de los movimientos rígidos y consideraciones sobre los giros.

**Comment by BlancaCC** [comment]
Hecho a falta de revisar en sección 2.4.1

**Comment by Exequielac** [comment]
Revisado y todo perfecto. Cierro la issue :D.
