### ISSUE TITLE
[Memoria] Mixing gradient

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/Mezclado-de-regiones-en-imagenes-usando-la-ecuacion-de-Poisson#43]
- Fundamento
- Descripción
- Implementación (breve comentario si procede)
- Resultados
- Refinamientos implementados
- Conclusiones
- Especular sobre refinamientos posibles (si procede).
- Otros comentarios oportunos.

**Comment by Exequielac** [comment]
Terminada la sección de Mixing Gradients de la memoria. Los apartados que se han considerado han sido: fundamento, descripción, breve comentario de implementación, resultados y conclusiones. Además, he dejado ideas para las conclusiones generales de la sección.

**Comment by BlancaCC** [comment]
Hola Exe, he revisado todo y está muy bien 😊, he cambiado/refinado los siguientes apartados que te pediría que volvieras a revisar y ya así darlo por cerrado el apartado: 
i) 4.1 Fundamento y descripción.
ii) Apartado 4.5 Conclusiones: he añadido en conclusión la ventaja que permite de relajar la región seleccionada. 
Manteniendo tus ideas he cambiado casi radicalmente la redacción de la conclusión, así que sería importante que la revisaras con cuidado. 

Ojo, sigue faltando al referencia a la imagen del arcoíris, hay que añadirla cuando se haga en #40.

**Comment by BlancaCC** [comment]
@BlancaCC Las imágenes se han descuadrado al añadir las regiones seleccionadas 😭

**Comment by Exequielac** [comment]
Lo he revisado y está genial :D. Dejo la issue abierta para no olvidarme de la referencia

**Comment by BlancaCC** [comment]
Ya he añadido la referencia, ¡ Un bicho menos queda!
