### ISSUE TITLE
[Memoria] Intercambio de características

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/Mezclado-de-regiones-en-imagenes-usando-la-ecuacion-de-Poisson#44]
- Fundamento
- Descripción
- Implementación (breve comentario si procede)
- Resultados
- Refinamientos implementados
- Conclusiones
- Especular sobre refinamientos posibles (si procede).
- Otros comentarios oportunos.

**Comment by Exequielac** [comment]
Pasada la técnica de intercambio de características al overleaf. Este era cortito :D.

**Comment by BlancaCC** [comment]
Revisado, todo correcto, he añadido referencia a una imagen y eso me ha movido la imagen y he tenido que añadir otra referencia 🤣

Maldito laTEX...
