### ISSUE TITLE
[Memoria] Aplanado de texturas

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/Mezclado-de-regiones-en-imagenes-usando-la-ecuacion-de-Poisson#45]
- Fundamento
- Descripción
- Implementación (breve comentario si procede)
- Resultados
- Refinamientos implementados
- Conclusiones
- Especular sobre refinamientos posibles (si procede).
- Otros comentarios oportunos.

**Comment by Exequielac** [comment]
Terminada la inclusión del aplanado de texturas en el overleaf, me he pasado más tiempo peleándome con las imágenes que otra cosa. Creo que ha quedado bien :D.

**Comment by BlancaCC** [comment]
Añado referencia de Cany de open cv, te pega mucho Exe usar ese detector, porque es muy CANY 🤣

Revisado y aprobado sin nada que cambiar. Maravilloso querido compañero 👏
