### ISSUE TITLE
[Memoria] Intercambio de color

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/Mezclado-de-regiones-en-imagenes-usando-la-ecuacion-de-Poisson#46]
- Fundamento
- Descripción
- Implementación (breve comentario si procede)
- Resultados
- Refinamientos implementados
- Conclusiones
- Especular sobre refinamientos posibles (si procede).
- Otros comentarios oportunos.

**Comment by Exequielac** [comment]
Ya he terminado de escribir la parte de esta técnica. Hay que revisar la organización de los apartados.

**Comment by BlancaCC** [comment]
@Exequielac Hay que revisar en el notebook, en el apartado de color, en la nota el siguiente fragmento de código


Nota: Se ha incluido en el experimento de la imagen de la manzana `Figura 65` el color de fondo, entendemos que puede hacer fluctuar los resultados, pero por ser su área considerablemente menor que la de la imagen fuente, pensamos que los resultados no afectarán en demasiado.

y cerciorarse de que la figura esté numerada correctamente. Porque en la imagen pone 75 y me imagino que has copiado y pegado el código de ahí. 

Te lo digo porque si estás tocando el código no quiero causarte un conflicto

**Comment by BlancaCC** [comment]
@BlancaCC @exequiielac mira este issue

**Comment by BlancaCC** [comment]
Vale no, ha sido error mío está correcto, perdón por el ajetreo

**Comment by BlancaCC** [comment]
Todo correcto, otro más finiquitadillo 🥳
