### ISSUE TITLE
Issue para ver cómo vamos pegando las figuras en el overleaf

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/Mezclado-de-regiones-en-imagenes-usando-la-ecuacion-de-Poisson#47]
1. Es necesario indicar que en la imagen aparece un número de figura, uno el respectivo índice que se puede encontrar en la implementación del código y otro el índice dentro de la memoria. 
2. Criterios o fragmentos que se están usando para escribir las imágenes.

**Comment by BlancaCC** [comment]
Un ejemplo de de dos imágenes una encima de otra en una misma figura: 
```
\begin{figure}[Ht]
 \centering
 \begin{subfigure}{.5\textwidth}
    \includegraphics[width=0.3\textwidth]{imagenes/PoissonImageEditing_cell_12_output_0.png}
    \label{fig:arcoiris}
    \caption{Arcoíris a copiar, imagen A}
  \end{subfigure}

 \begin{subfigure}{.5\textwidth}
   \centering
    \includegraphics[width=0.3\textwidth]{imagenes/PoissonImageEditing_cell_8_output_3.png}
    \caption{Playa sobre la que colocar el arcoíris}
    \label{f:tigre}
    \end{subfigure}
 \label{f:arcoiris-playa}
\caption{Imágenes A y B}
\end{figure}

```
Produciendo esto 
<img width="603" alt="Captura de pantalla 2022-01-20 a las 17 23 13" src="https://user-images.githubusercontent.com/32298296/150379409-fd015a21-f46f-47db-967d-f99d75a9f342.png">

**Comment by BlancaCC** [comment]
No consigo que se referencie bien las figuras :( 

Un ejemplo del error: 
<img width="1512" alt="Captura de pantalla 2022-01-20 a las 17 46 39" src="https://user-images.githubusercontent.com/32298296/150383840-fe347c85-8f9c-47b0-bd1f-79836031c0d1.png">

**Comment by BlancaCC** [comment]
El problema estaba en el orden de las etiquetas label y caption. Debe ser el que sigue: 
```
    \caption{Elementos y resultado de clonado directo}
    \label{fig:copiadoRegionesConexasClonadoDirecto}
\end{figure}
```

**Comment by Exequielac** [comment]
Siguiendo https://es.overleaf.com/learn/latex/How_to_Write_a_Thesis_in_LaTeX_(Part_3)%3A_Figures%2C_Subfigures_and_Tables he añadido dos paquetes. Al añadirlos, saltaban varios errores de escape en todo el documento que he arreglado. Ahora se debe de seguir el formato para que aparezcan horizontalmente.
