### ISSUE TITLE
[Memoria] Hablar sobre criterio para medir la bondad del ajuste

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/Mezclado-de-regiones-en-imagenes-usando-la-ecuacion-de-Poisson#48]
En un principio pensé en hacerlo por inspección directa.

En este artículo: https://pdfs.semanticscholar.org/8047/878b22d4f42ebcf0eff2dcf1929a535dbad4.pdf

Utiliza la inspección visual y MSE

**Comment by BlancaCC** [comment]
2.4.3 Finiquitado a falta de revisión 😊

**Comment by Exequielac** [comment]
El apartado está genial, he estado pensando si habría que añadir algo más pero no se me ha ocurrido nada. Cierro la issue :D.

**Comment by BlancaCC** [comment]
@Exequielac jsjjsjs es que ahí está el asunto
