### ISSUE TITLE
[Memoria] Comentarios sobre la memoria

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/Mezclado-de-regiones-en-imagenes-usando-la-ecuacion-de-Poisson#51]
Añado subvención dentro de la introducción 1.1 \subsection{Comentarios sobre la memoria}  

En ella comento sobre la numeración de la figura (porque aparecen dos numeraciones, la del notebook y la de la memoria) 

Y también sobre las referencias a código

**Comment by Exequielac** [comment]
Lo leí antes y lo he vuelto a revisar. Había un pequeño error con el símbolo # que ya he solucionado. Cierro la issue
