### ISSUE TITLE
[Memoria] Cambios de iluminación locales

### ISSUE THREAD

**Issue by Exequielac** [BlancaCC/Mezclado-de-regiones-en-imagenes-usando-la-ecuacion-de-Poisson#52]
Seguir la estructura común de las técnicas

**Comment by Exequielac** [comment]
Terminada de escribir la parte de cambios de iluminación. Revisar distribución de imágenes.

**Comment by BlancaCC** [comment]
Revisado y añadido referencia a Poisson, 
Falta que se añada la referencia HDR, no sé muy bien cuál es del notebook así que mejor dejo que la añadas tú y cierres el ISSUE con ello

**Comment by Exequielac** [comment]
Ya está referenciado :D. Cierro la issue.
