### ISSUE TITLE
[Memoria] Cambios de color locales

### ISSUE THREAD

**Issue by Exequielac** [BlancaCC/Mezclado-de-regiones-en-imagenes-usando-la-ecuacion-de-Poisson#53]
Escribir en memoria siguiendo la estructura común

**Comment by Exequielac** [comment]
Ya está escrita la parte de cambios de iluminación locales :D.

**Comment by BlancaCC** [comment]
Otro artículo revisado. 
Madre mía será que estoy ya delirando, pero esta parte me parece monísima :D
