### ISSUE TITLE
[Memoria] Añadir comentario sobre movimientos rígido y porqué son estos

### ISSUE THREAD

**Issue by BlancaCC** [BlancaCC/Mezclado-de-regiones-en-imagenes-usando-la-ecuacion-de-Poisson#55]

**Comment by BlancaCC** [comment]
Comentar porqué utilizar movimientos rígidos translaciones, simetría  y giros de manera teórica. 

Pero como en la práctica también se desaconsejan los giros (al menos con este sistema)

Comentar otro sistema en el que se selecciona también la posición de cada pixel de destino (trasladando la máscara) 
Pero con procedimientos manuales como los nuestros eso era inviable.

**Comment by BlancaCC** [comment]
Otro apartado acabado a revisar en 2.4.2

**Comment by Exequielac** [comment]
Revisado, he cambiado un poco el formato. Revísalo y si te gusta cierra la issue :D.

**Comment by BlancaCC** [comment]
@Exequielac Genial, voy a verlo

**Comment by BlancaCC** [comment]
Lo has dejado genial, gracias por cuidar la presentación 🥰
